rm(list = ls())
setwd("~/Desktop/Agronomic-problems/Agronomic-problems")
library(tidyverse)
data1 = read.csv("Grain_N_rate_trial_harvest_data_2021.csv")
data1$Block= as.factor(data1$Block)
data1$Variety = as.factor(data1$Variety)
data1$N_rates = as.factor(data1$N_rates)
1:ncol(data1)
data1$Plant_height = log(data1$Plant_height)
data1$Seed_yield = log(data1$Seed_yield)
data1$TS_1 = log(data1$TS_1)
data1$TS_2 = log(data1$TS_2)
data1$TP_1= log(data1$TP_1)
table(data1$N_rates)
plot = list()
model1= list()
HSD = list()
Shapiro = list()
MSerror = list()
library(agricolae)
sink("Anova_Results.doc")
for(i in 5:ncol(data1)){
  column = names(data1[i])
  model1 = lm((data1[,i]~ data1$N_rates*Variety + Block), data = data1)
  anova = anova(lm((data1[,i]~ data1$N_rates*Variety + Block), data = data1))
  Shapiro = shapiro.test(model1$resid)
  print(column)
  print(anova)
  print(Shapiro)
  print(HSD)
}
sink()
data$
  HSD = HSD.test (model1, trt = c("N_rates"), group = TRUE, console=TRUE)
 
df = df.residual(model1)
MSerror = deviance(model1)/df
with(data1,HSD.test (data1[i], N_rates, df, MSerror, group = TRUE, console=TRUE)